baseURL = "https://hayabusa1601.github.io/"
languageCode = "zh-cn"
title = "ハヤブサの巣窟"
theme = "github-style"
googleAnalytics = "UA-123456-789"
pygmentsCodeFences = true
pygmentsUseClasses = true

[params]
  author = "ハヤブサ"
  description = "九州のお臍の高専生の雑記"
  github = "Hayabusa1601"
  twitter = "Hayabusa1601"
  email = "1601hayabusa@gmail.com"
  url = "https://hayabusa1601.net"
  keywords = "blog, google analytics"
  reddit = "Hayabusa1601"
  rss = true
  lastmod = true
  favicon = "images/favicon.png"
  location = "Japan"
  header_image   = "images/mycon.jpg"

  twitterusername = "ハヤブサ"
  twitterid = "@Hayabusa1601"
  creator = "Hayabusa"
  creatorid = "@Hayabusa1601"
  description = "九州のお臍の高専生の雑記"
  twittertitle = "ハヤブサの巣窟"
  title = "巣窟"
  twitterthumbnail = "images/mycon.jpg"


[frontmatter]
  date = ["date", "publishDate", "lastmod"]
  lastmod = [":git", "lastmod", "date", "publishDate"]
  publishDate = ["publishDate", "date"]
  expiryDate = ["expiryDate"]