baseURL = "https://hayabusa1601.github.io/"
languageCode = "zh-cn"
title = "はやぶろぐ (仮)"
theme = "github-style"
googleAnalytics = "UA-123456-789"
pygmentsCodeFences = true
pygmentsUseClasses = true

[params]
  author = "ハヤブサ"
  description = "九州のお臍の高専生です。"
  github = "Hayabusa1601"
  twitter = "Hayabusa1601"
  email = "1601hayabusa@gmail.com"
  url = "https://hayabusa1601.com"
  keywords = "blog, google analytics"
  reddit = "Hayabusa1601"
  rss = true
  lastmod = true
  favicon = "images/favicon.png"
  location = "Japan"



[frontmatter]
  date = ["date", "publishDate", "lastmod"]
  lastmod = [":git", "lastmod", "date", "publishDate"]
  publishDate = ["publishDate", "date"]
  expiryDate = ["expiryDate"]