baseURL = "https://blog.hayabusa1601.net/"
languageCode = "zh-ja"
title = "ハヤブサの巣窟"
theme = "github-style"
lastmod = true
googleAnalytics = "G-VLDYHH5Z39"
pygmentsCodeFences = true
pygmentsUseClasses = true

[params]
  author = "Hayabusa"
  description = "九州の理系学生の雑記"
  github = "Hayabusa1601"
  twitter = "Hayabusa1601"
  email = "1601hayabusa@gmail.com"
  url = "https://hayabusa1601.net"
  keywords = "blog, google analytics"
  reddit = "Hayabusa1601"
  rss = true
  lastmod = true
  favicon = "images/favicon.png"
  location = "Japan"
  avator = "/images/avator.png"
  images = ["images/mycon.jpg"]
  title = "ハヤブサの巣窟"


[frontmatter]
  date = ["date", "publishDate", "lastmod"]
  lastmod = [":git", "lastmod", "date", "publishDate"]
  publishDate = ["publishDate", "date"]
  expiryDate = ["expiryDate"]